version: "3.7"
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=America/Edmonton
        ports:
            - '5432:5432'
        volumes: 
            - ./bkp:/host/bkp:rw
            - db:/var/lib/postgresql/data
volumes:
    db:
      driver: local